// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvSZsrn-nyrhfn9-QDarI-2L2PlY8Gzg',
    appId: '1:838116745875:web:72c9039260288652986366',
    messagingSenderId: '838116745875',
    projectId: 'trackdev-80ed8',
    authDomain: 'trackdev-80ed8.firebaseapp.com',
    storageBucket: 'trackdev-80ed8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaelXYVFawSpG6wgI5pX9FgyAp9VaEkZY',
    appId: '1:838116745875:android:836e278ab3e3e0ae986366',
    messagingSenderId: '838116745875',
    projectId: 'trackdev-80ed8',
    storageBucket: 'trackdev-80ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdhRj3jlQ-IZmuhnDyHmvh234XVlu0bUw',
    appId: '1:838116745875:ios:2a85c1f3d620ea24986366',
    messagingSenderId: '838116745875',
    projectId: 'trackdev-80ed8',
    storageBucket: 'trackdev-80ed8.firebasestorage.app',
    iosBundleId: 'com.example.trackdevApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdhRj3jlQ-IZmuhnDyHmvh234XVlu0bUw',
    appId: '1:838116745875:ios:2a85c1f3d620ea24986366',
    messagingSenderId: '838116745875',
    projectId: 'trackdev-80ed8',
    storageBucket: 'trackdev-80ed8.firebasestorage.app',
    iosBundleId: 'com.example.trackdevApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDvSZsrn-nyrhfn9-QDarI-2L2PlY8Gzg',
    appId: '1:838116745875:web:04a8072dda9c5558986366',
    messagingSenderId: '838116745875',
    projectId: 'trackdev-80ed8',
    authDomain: 'trackdev-80ed8.firebaseapp.com',
    storageBucket: 'trackdev-80ed8.firebasestorage.app',
  );
}
